# Generated by Django 5.0.3 on 2024-03-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0002_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
