# Generated by Django 5.0.3 on 2024-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0009_category_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('title', models.CharField(max_length=225)),
                ('title_en', models.CharField(max_length=225, null=True)),
                ('title_tr', models.CharField(max_length=225, null=True)),
                ('keywords', models.CharField(max_length=225)),
                ('keywords_en', models.CharField(max_length=225, null=True)),
                ('keywords_tr', models.CharField(max_length=225, null=True)),
                ('description', models.CharField(max_length=225)),
                ('description_en', models.CharField(max_length=225, null=True)),
                ('description_tr', models.CharField(max_length=225, null=True)),
                ('phone_fixed', models.CharField(max_length=15)),
                ('phone_mobile', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
